run-python:
	python main.py

# Need to install stanford nltk before running this
run-java:
	cd stanford-corenlp-full-2018-10-05 && java -mx5g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -timeout 30000

